log_artifact: 'FALSE'
experiment_name: "mlflow_experiment"
tags: 
  test: "TRUE"
  model_type: transformer
nested_run: "FALSE"
run_id: null
flatten_params: "FALSE"
tracking_uri: null
logging_dir: null
run_name: null
description: null