# Default configuration

defaults:
  - data: default
  - training_arguments: default
  - model: default
  - mlflow: default
  - wandb: default
  - _self_ # attributes in this file will override defaults


model:
  model_name_or_path:  "sentence-transformers/all-mpnet-base-v2"
  freeze_first_model: yes
  max_chunks: 128
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 2048
  hidden_act: gelu
  dropout: 0.1
  layer_norm_eps: 1e-7

  
data:
  max_seq_length: 256
  pad_multiple: 8
  stride: null # set to `null` to not use Strideformer
  n_rows: 10000
  map_batch_size: 500 # batch size when using `datasets.map`
  dataset_name: ccdv/arxiv-classification
  dataset_config_name: no_ref
  
training_arguments:
  do_train: yes
  do_eval: yes
  
  fp16: yes
  
  learning_rate: 7e-6
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 128
  gradient_accumulation_steps: 1
  
  metric_for_best_model: "f1_micro"
  greater_is_better: yes
  report_to: "wandb"
  log_level: "warning"
  save_strategy: "epoch"
  logging_steps: 20
  save_total_limit: 2
  evaluation_strategy: "steps"
  eval_steps: 150
  
# general configuration
num_proc: 7
task: text-classification
language: en
project_name: stride-former

hydra:
  output_subdir: config